# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop,release ]
  pull_request:
    branches: [ develop ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
    - run: npm ci
    - name: Install Angular CLI
      run: npm install -g @angular/cli
    - name: Download firebase install script
      run: curl -sL https://firebase.tools >> firebase-tools.sh
    - name: Install Firebase
      run: bash firebase-tools.sh
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        tag: node-${{ matrix.node }}
        build: bash firebase-tools.sh
        start: node -v
        command: firebase emulators:exec --only auth --project turma-de-elite-app './run_tests.sh'
    - name: Build application
      run: ng build --prod
    - name: Deploy on Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      if: github.ref == 'refs/heads/release'
      with:
        repoToken: "${{ secrets.GITHUB_TOKEN }}"
        firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TURMA_DE_ELITE_APP}}"
        channelId: live
        projectId: turma-de-elite-app
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      
